{% set name = "harlequin-bigquery" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin_bigquery-{{ version }}.tar.gz
  sha256: 8dd0f099f894ef1e33978860d767afacfa8b1333c1d8cf3fd473787743751094

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - harlequin >=1.7,<3
    - google-cloud-bigquery-core >=3.14.1,<4.0.0
    - google-cloud-bigquery-storage >=2.24.0,<3.0.0

test:
  imports:
    - harlequin_bigquery
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/joshtemple/harlequin-bigquery
  summary: A Harlequin adapter for Google BigQuery.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/harlequin
